modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"

[[mods]]
modId = "foxiemc"
version = "0.1.0"
displayName = "FoxieMC"
authors = "Made with love by mystical foxie"
description = '''
This mod adds a little companion to your game called Foxie.
It behaves a lot like a fox, but... I dont want to spoil you there. ;p
#WorkInProgress (Many new features are on the roll for the near future)
'''

[[dependencies.foxiemc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foxiemc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"
